language: objective-c

branches:
  only:
    - master

before_install:
  - git submodule update --init --recursive
  - brew update || brew update
  - brew outdated carthage || brew upgrade carthage
  - sh bin/setup

xcode_project: SwiftyOAuth.xcodeproj
xcode_scheme: SwiftyOAuthTests
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3

script:
  - xcodebuild test -project SwiftyOAuth.xcodeproj -scheme SwiftyOAuthTests -destination "platform=iOS Simulator,name=iPhone 6s"
