language: objective-c

branches:
  only:
    - master

xcode_project: SwiftyOAuth.xcodeproj
xcode_scheme: SwiftyOAuthTests
osx_image: xcode10.2
xcode_sdk: iphonesimulator10.0

script:
  - xcodebuild test -project SwiftyOAuth.xcodeproj -scheme SwiftyOAuthTests -destination "platform=iOS Simulator,name=iPhone 6s"
